export default function PrivacyPolicy() {
  return (
    <div className="container mx-auto px-4 py-8 bg-white shadow-lg rounded-lg my-8">
      <h1 className="text-4xl font-bold mb-6 text-gray-900">FlowDo – Personal Productivity Mobile App</h1>
      <p className="mb-4 text-gray-700"><strong>Effective Date: 18th August 2025</strong></p>
      <p className="mb-4 text-gray-700"><strong>Last Updated: 18th August 2025</strong></p>
      <p className="mb-4 text-gray-700">Hey there! At FlowDo, we’re all about helping you master your productivity, and that means keeping your data safe and sound. This Privacy Policy (“Policy”) explains how FlowDo (referred to as “FlowDo,” “we,” “us,” or “our”), collects, uses, and protects your info when you use our mobile application (the “App”) or related services. By using the App, you’re cool with this Policy and our Terms of Service at [flowdo.com/terms-of-service]. Questions? Hit us up at <strong>support@flowdo.com</strong>.</p>

      <h2 className="text-3xl font-semibold mt-8 mb-4 text-gray-800">What We Collect</h2>
      <h3 className="text-2xl font-medium mt-6 mb-3 text-gray-800">Personal Stuff:</h3>
      <p className="mb-4 text-gray-700">When you sign up or use the App, we grab details like your name, email, and whatever you toss into your account profile.</p>

      <h3 className="text-2xl font-medium mt-6 mb-3 text-gray-800">Usage Vibes:</h3>
      <p className="mb-4 text-gray-700">We track how you interact with the App—think features used, tasks created, and timestamps—to make it better.</p>

      <h3 className="text-2xl font-medium mt-6 mb-3 text-gray-800">App Data:</h3>
      <p className="mb-4 text-gray-700">Data you input into the App (like tasks, projects, notes) and the data generated by your use of the App (e.g., task completion status, project progress) get collected to keep the App running smooth and provide its core functionality.</p>

      <h3 className="text-2xl font-medium mt-6 mb-3 text-gray-800">Tech Bits:</h3>
      <p className="mb-4 text-gray-700">Device type, operating system, unique device identifiers, and analytics data—we snag these to keep things secure and tweak your experience. We do not use cookies in the mobile app context.</p>

      <h2 className="text-3xl font-semibold mt-8 mb-4 text-gray-800">How We Use Your Info</h2>
      <h3 className="text-2xl font-medium mt-6 mb-3 text-gray-800">Run the Show:</h3>
      <p className="mb-4 text-gray-700">Your data powers account setup, App access, and those productivity features you love.</p>

      <h3 className="text-2xl font-medium mt-6 mb-3 text-gray-800">Make It Better:</h3>
      <p className="mb-4 text-gray-700">We analyze usage to level up features, fix bugs, and improve your productivity experience.</p>

      <h3 className="text-2xl font-medium mt-6 mb-3 text-gray-800">Talk to You:</h3>
      <p className="mb-4 text-gray-700">Emails about updates, support, or important notifications—only what’s needed, no spam vibes.</p>

      <h3 className="text-2xl font-medium mt-6 mb-3 text-gray-800">Legal Stuff:</h3>
      <p className="mb-4 text-gray-700">We use it to comply with laws, handle disputes, or protect our rights if things get messy.</p>

      <h2 className="text-3xl font-semibold mt-8 mb-4 text-gray-800">Who We Share With</h2>
      <h3 className="text-2xl font-medium mt-6 mb-3 text-gray-800">Our Crew:</h3>
      <p className="mb-4 text-gray-700">Employees and contractors get access only if they need it to deliver the App’s services—strict confidentiality rules apply.</p>

      <h3 className="text-2xl font-medium mt-6 mb-3 text-gray-800">Tech Partners:</h3>
      <p className="mb-4 text-gray-700">Cloud providers (e.g., for data storage) or analytics tools help us host and improve the App—they’re bound by tight data agreements.</p>

      <h3 className="text-2xl font-medium mt-6 mb-3 text-gray-800">Legal Needs:</h3>
      <p className="mb-4 text-gray-700">If the law knocks (e.g., court order), we’ll share what’s required, but we’ll let you know first unless gagged.</p>

      <h3 className="text-2xl font-medium mt-6 mb-3 text-gray-800">No Selling:</h3>
      <p className="mb-4 text-gray-700">Your data’s not for sale—period.</p>

      <h2 className="text-3xl font-semibold mt-8 mb-4 text-gray-800">Your Choices</h2>
      <h3 className="text-2xl font-medium mt-6 mb-3 text-gray-800">Control It:</h3>
      <p className="mb-4 text-gray-700">Update your account info or opt out of non-essential emails via <strong>support@flowdo.com</strong>.</p>

      <h3 className="text-2xl font-medium mt-6 mb-3 text-gray-800">App Data:</h3>
      <p className="mb-4 text-gray-700">You decide what data to input into the App—less input, less collected.</p>

      <h2 className="text-3xl font-semibold mt-8 mb-4 text-gray-800">Data Protection</h2>
      <h3 className="text-2xl font-medium mt-6 mb-3 text-gray-800">Security:</h3>
      <p className="mb-4 text-gray-700">We lock it down with encryption, access controls, and regular checks—industry-standard stuff to keep hackers out.</p>

      <h3 className="text-2xl font-medium mt-6 mb-3 text-gray-800">Location:</h3>
      <p className="mb-4 text-gray-700">Data’s stored in <strong>India</strong> on secure cloud servers.</p>

      <h3 className="text-2xl font-medium mt-6 mb-3 text-gray-800">No Guarantees:</h3>
      <p className="mb-4 text-gray-700">We hustle to protect it, but no system’s 100%—we’ll notify you fast if a breach hits.</p>

      <h2 className="text-3xl font-semibold mt-8 mb-4 text-gray-800">Retention</h2>
      <h3 className="text-2xl font-medium mt-6 mb-3 text-gray-800">How Long:</h3>
      <p className="mb-4 text-gray-700">We keep your data while your account’s active and for <strong>1 year</strong> after, unless law says otherwise—then we shred it.</p>

      <h3 className="text-2xl font-medium mt-6 mb-3 text-gray-800">Post-Termination:</h3>
      <p className="mb-4 text-gray-700">Cancel your subscription? We hold data for <strong>30 days</strong> so you can grab it, then it’s gone.</p>

      <h2 className="text-3xl font-semibold mt-8 mb-4 text-gray-800">Your Rights</h2>
      <h3 className="text-2xl font-medium mt-6 mb-3 text-gray-800">Access & Fix:</h3>
      <p className="mb-4 text-gray-700">Want to see or tweak your data? Email <strong>support@flowdo.com</strong>—we’ll hook you up within <strong>30 days</strong>.</p>

      <h3 className="text-2xl font-medium mt-6 mb-3 text-gray-800">Delete It:</h3>
      <p className="mb-4 text-gray-700">Ask us to wipe your personal info—we’ll do it unless we’re legally stuck keeping it.</p>

      <h3 className="text-2xl font-medium mt-6 mb-3 text-gray-800">Complain:</h3>
      <p className="mb-4 text-gray-700">Not vibin’ with how we handle your data? Reach out, or escalate to India’s Data Protection Authority when it’s live.</p>

      <h2 className="text-3xl font-semibold mt-8 mb-4 text-gray-800">Kids</h2>
      <h3 className="text-2xl font-medium mt-6 mb-3 text-gray-800">No Kiddos:</h3>
      <p className="mb-4 text-gray-700">The App isn’t for anyone under 13—we’re sorry, young productivity enthusiasts!</p>

      <h2 className="text-3xl font-semibold mt-8 mb-4 text-gray-800">Third-Party Links</h2>
      <h3 className="text-2xl font-medium mt-6 mb-3 text-gray-800">External Vibes:</h3>
      <p className="mb-4 text-gray-700">We might link to other sites or tools—they’ve got their own rules, so check ‘em out. We’re not liable for their moves.</p>

      <h2 className="text-3xl font-semibold mt-8 mb-4 text-gray-800">Changes to This Policy</h2>
      <h3 className="text-2xl font-medium mt-6 mb-3 text-gray-800">Updates:</h3>
      <p className="mb-4 text-gray-700">We’ll tweak this Policy as needed—new versions will be available within the App and on our website at [flowdo.com/privacy-policy]. Big changes? We’ll email you. Keep using the App, and you’re down with the latest.</p>

      <h2 className="text-3xl font-semibold mt-8 mb-4 text-gray-800">Governing Law</h2>
      <h3 className="text-2xl font-medium mt-6 mb-3 text-gray-800">Law Vibes:</h3>
      <p className="mb-4 text-gray-700">This Policy rolls under Indian law, with disputes handled in Mumbai courts or via arbitration per our Terms of Service.</p>
    </div>
  );
}
